apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: paymentservice
  name: paymentservice
spec:
  replicas: 3
  selector:
      matchLabels:
        app: paymentservice
  strategy:
      rollingUpdate:
          maxUnavailable: 1
          maxSurge: 0
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - image: spanov1980/microservices-demo-paymentservice:v0.0.2
        name: paymentservice
        env:
        - name: PORT
          value: "50051"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        - name: DISABLE_DEBUGGER
          value: "1"
